# Generated by Django 3.0.3 on 2021-08-06 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VkUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(default=0)),
                ('user_img', models.CharField(default='Не указано', max_length=300)),
                ('user_name', models.CharField(default='Не указано', max_length=300)),
                ('token', models.CharField(default='', max_length=300)),
                ('is_admin', models.BooleanField(default=False)),
            ],
        ),
    ]
