# Generated by Django 3.0.3 on 2021-08-28 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210812_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='wallet',
            field=models.BigIntegerField(default=0),
        ),
    ]
