# Generated by Django 3.0.3 on 2021-08-12 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Не указано', max_length=300)),
                ('photo', models.TextField(default='')),
                ('vk_id', models.IntegerField(default=-1, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='AccountPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.IntegerField(default=0)),
                ('client_id', models.IntegerField(default=-1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_actor', to='cabinets.ClientUser')),
            ],
            options={
                'unique_together': {('user', 'client_id')},
            },
        ),
    ]
