# Generated by Django 3.0.3 on 2021-08-28 11:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cabinets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_complete', models.BooleanField(default=False)),
                ('terminal_key', models.TextField(default='')),
                ('payment_id', models.TextField(default='')),
                ('order_id', models.TextField(default='')),
                ('amount', models.BigIntegerField(default=0)),
                ('payment_url', models.TextField(default='')),
                ('is_wallet', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_actor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
