# Generated by Django 3.0.3 on 2021-08-28 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinets', '0002_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='is_complete',
        ),
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='payment',
            name='token',
            field=models.TextField(default=''),
        ),
    ]
