# Generated by Django 3.0.3 on 2021-08-31 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinets', '0004_auto_20210830_1706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='token',
        ),
        migrations.AddField(
            model_name='payment',
            name='date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
